spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql:///batch_cmd

  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8081